export const CODE_CHANGED = "CODE_CHANGED";
export const SCOPE_UPDATED = "SCOPE_UPDATED";
export const HIGHLIGHT_MARKER_APPENDED = "HIGHLIGHT_MARKER_APPENDED";
export const NEXT_STEP_DECIDED = "NEXT_STEP_DECIDED";
export const OPERATION_TYPE_UPDATED = "OPERATION_TYPE_UPDATED";
